output_path: "/mnt/d/output"

simulation:
  is_synchronous_mode: False
  frame_rate: 10
  warmup_seconds: 0.7
  duration_seconds: 8
  queue_timeout: 60.0
  client_timeout: 20.0
  spectator_height: 120
  # Settings for a sunny day
  weather:
    cloudiness: 10.0
    precipitation: 0.0
    fog_density: 0.0
    sun_altitude_angle: 65.0
    sun_azimuth_angle: 180.0
    rayleigh_scattering_scale: 0.0331
  preferred_vehicles:
    - "vehicle.tesla.model3"

scenario:
  map: "Town03"
  # Ranks of vehicles (sorted by distance to spawn_center) to be selected as CAVs
  desired_cav_ranks: [0]
  spawn_center: {x: -28, y: 164, z: 0}
  # Locations for each RSU, identified by their index
  rsu_transform:
    - { location: {x: -19, y: 184, z: 0}, rotation: {yaw: -30, roll: 0, pitch: 0} }
    - { location: {x: -35, y: 186, z: 0}, rotation: {yaw: 223.65, roll: 0, pitch: 0} }

# Sensor definitions, attributes, and relative placements
sensors:
  cav:
    camera0:
      blueprint: "sensor.camera.rgb"
      attributes:
        image_size_x: '640'
        image_size_y: '480'
        fov: '110'
      transform:
        location: {x: 1.5, y: 0.0, z: 2.4}
        rotation: {yaw: 0, roll: 0, pitch: 0}
    camera1:
      blueprint: "sensor.camera.rgb"
      attributes:
        image_size_x: '640'
        image_size_y: '480'
        fov: '110'
      transform:
        location: {x: -1.5, y: 0.0, z: 2.4}
        rotation: {yaw: 180, roll: 0, pitch: 0}
    camera2:
      blueprint: "sensor.camera.rgb"
      attributes:
        image_size_x: '640'
        image_size_y: '480'
        fov: '110'
      transform:
        location: {x: 0.0, y: -0.7, z: 2.4}
        rotation: {yaw: -90, roll: 0, pitch: 0}
    camera3:
      blueprint: "sensor.camera.rgb"
      attributes:
        image_size_x: '640'
        image_size_y: '480'
        fov: '110'
      transform:
        location: {x: 0.0, y: 0.7, z: 2.4}
        rotation: {yaw: 90, roll: 0, pitch: 0}
    lidar:
      blueprint: "sensor.lidar.ray_cast"
      attributes:
        range: '120.0'
        channels: '64'
        points_per_second: '3000000' # 30k * 100fps
        rotation_frequency: '100' # Matches frame_rate
        upper_fov: '2'
        lower_fov: '-25'
        dropoff_general_rate: '0.0'
        dropoff_intensity_limit: '1.0'
      transform:
        location: {x: 0.0, y: 0.0, z: 2.5}
        rotation: {yaw: 0, roll: 0, pitch: 0}
    imu:
      blueprint: "sensor.other.imu"
      attributes:
        noise_accel_stddev_x: '0.1'
        noise_accel_stddev_y: '0.1'
        noise_accel_stddev_z: '0.1'
        noise_gyro_stddev_x: '0.002'
        noise_gyro_stddev_y: '0.002'
        noise_gyro_stddev_z: '0.002'
        noise_gyro_bias_x: '0.001'
        noise_gyro_bias_y: '0.001'
        noise_gyro_bias_z: '0.001'
        noise_seed: '42'
      transform:
        location: {x: 0.0, y: 0.0, z: 0.0}
        rotation: {yaw: 0, roll: 0, pitch: 0}
  rsu:
    camera:
      blueprint: "sensor.camera.rgb"
      attributes:
        image_size_x: '640'
        image_size_y: '480'
        fov: '110'
      transform:
        location: {x: 0, y: 0, z: 3.9}
        rotation: {pitch: 0, yaw: -90, roll: 0}
    depth_camera:
      blueprint: "sensor.camera.depth"
      attributes:
        image_size_x: '640'
        image_size_y: '480'
        fov: '110'
      transform:
        location: {x: 0, y: 0, z: 3.9}
        rotation: {pitch: 0, yaw: -90, roll: 0}
    lidar:
      blueprint: "sensor.lidar.ray_cast"
      attributes:
        range: '120.0'
        channels: '64'
        points_per_second: '3000000' # 30k * 100fps
        rotation_frequency: '100' # Matches frame_rate
        upper_fov: '2'
        lower_fov: '-25'
        dropoff_general_rate: '0.0'
        dropoff_intensity_limit: '1.0'
      transform:
        location: {x: 0, y: 0, z: 4}
        rotation: {pitch: 0, yaw: -90, roll: 0}
    radar:
      blueprint: "sensor.other.radar"
      attributes:
        horizontal_fov: '110'
        vertical_fov: '30'
        range: '100'
        points_per_second: '200000'
      transform:
        location: {x: 0, y: 0, z: 4.1}
        rotation: {yaw: -90, pitch: 0, roll: 0}

sionna_simulation:
  gpu_num: 0
  planar_array_tx:
    num_rows: 1
    num_cols: 16
    vertical_spacing: 0.5
    horizontal_spacing: 0.5
    pattern: "dipole"
    polarization: "V"
  planar_array_rx:
    num_rows: 1
    num_cols: 16
    vertical_spacing: 0.5
    horizontal_spacing: 0.5
    pattern: "dipole"
    polarization: "V"
  fc: 5000000000
  num_subcarriers: 128
  subcarrier_spacing: 30000
  paths_solver:
    max_depth: 1
    max_num_paths_per_src: 1000000
    samples_per_src: 1000000
    synthetic_array: True
  cir:
    num_time_steps: 3
  cfr:
    num_time_steps: 3

sionna_materials:
#  very_dry_ground:
#    thickness: 0.1
#    relative_permittivity: 3
#    conductivity: 2.5
#    scattering_coefficient: 0.0
#    xpd_coefficient: 0.0
#    scattering_pattern: lambertian